FROM quay.io/sampandey001/secktor
RUN git clonehhttps://github.com/kanishkadesilva/QUEEN-THARU-MD /root/kanishkadesilva
WORKDIR /root/kanishkadesilva/
RUN npm install npm@latest
RUN npm install
EXPOSE 8000
CMD ["npm", "start"]
